# Generated by Django 5.1.1 on 2025-08-25 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='certifications',
            field=models.FileField(blank=True, null=True, upload_to='certifications/'),
        ),
    ]
