# Generated by Django 5.1.1 on 2025-08-24 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interview',
            old_name='rating',
            new_name='rating_by_recruiter',
        ),
    ]
