# Generated by Django 5.1.1 on 2025-08-25 07:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_rename_rating_interview_rating_by_recruiter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='mode',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Zoom', 'Zoom'), ('Google Meet', 'Google Meet')], default='Online', max_length=50),
        ),
        migrations.AlterField(
            model_name='interview',
            name='scheduled_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
